import { create } from 'zustand';
import { shallow } from 'zustand/shallow';

// Pending ID is the next package label, generated by the user clicking
// "Nouveau colis". When a measurement arrives, it inherits this ID
// (overriding any incoming barcode), then the slot clears so the next
// click is required before a new package is recorded.
const COUNTER_KEY = 'mobilax.dailyCounter';

function loadCounter() {
  try {
    const raw = JSON.parse(localStorage.getItem(COUNTER_KEY) || '{}');
    if (raw.day === todayKey()) return raw.value || 0;
  } catch {}
  return 0;
}

function saveCounter(value) {
  try { localStorage.setItem(COUNTER_KEY, JSON.stringify({ day: todayKey(), value })); } catch {}
}

function todayKey() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
}

function appendEvent(log, entry) {
  const next = [...log, { ...entry, t: Date.now() }];
  return next.length > 100 ? next.slice(-100) : next;
}

function buildPendingId(n) {
  const d = new Date();
  const ymd = `${String(d.getFullYear()).slice(2)}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;
  return `MBX-${ymd}-${String(n).padStart(4, '0')}`;
}

export const useMeasureStore = create((set, get) => ({
  measure: null,
  status: 'idle',
  connection: 'disconnected',
  error: null,
  receivedAt: null,
  measureCount: 0,

  pendingId: null,
  dailyCounter: loadCounter(),

  liveWeight: null,
  liveStable: false,
  serialStatus: 'unknown', // 'open' | 'error' | 'closed' | 'unknown'
  serialError: null,
  serialPath: null,
  eventLog: [], // chronological feed of activity (user actions + serial + measure lifecycle)
  setSerialStatus: ({ status, error, path }) => set({ serialStatus: status, serialError: error ?? null, serialPath: path ?? null }),
  pushEvent: (entry) => set((s) => {
    const next = [...s.eventLog, { ...entry, t: Date.now() }];
    return { eventLog: next.length > 100 ? next.slice(-100) : next };
  }),
  setLiveWeight: ({ weight, stable }) => set((s) => {
    const next = { liveWeight: weight, liveStable: !!stable };
    // When a stable weight lands while a pending ID is armed, lock it as the current measure.
    if (stable && s.pendingId && weight != null) {
      next.measure = {
        barcode: s.pendingId,
        codeSource: 'generated',
        datetime: new Date().toISOString().replace('T', ' ').slice(0, 19),
        weight,
        len: null, width: null, height: null, vol: null,
      };
      next.status = 'ready';
      next.receivedAt = Date.now();
      next.measureCount = s.measureCount + 1;
      next.pendingId = null;
    }
    return next;
  }),

  // Generates the next pending ID and arms the slot.
  newPackage: () => set((s) => {
    const next = s.dailyCounter + 1;
    saveCounter(next);
    const id = buildPendingId(next);
    return {
      dailyCounter: next,
      pendingId: id,
      status: 'measuring',
      eventLog: appendEvent(s.eventLog, { kind: 'user.new', text: `Nouveau colis armé — ${id}` }),
    };
  }),

  setMeasure: (measure) => set((s) => {
    const m = s.pendingId
      ? { ...measure, barcode: s.pendingId, codeSource: 'generated' }
      : measure;
    return {
      measure: m,
      status: 'ready',
      error: null,
      receivedAt: Date.now(),
      measureCount: s.measureCount + 1,
      pendingId: null,
      eventLog: appendEvent(s.eventLog, {
        kind: 'measure.locked',
        text: `Mesure verrouillée — ${m.barcode} | ${m.weight ?? '—'} kg`,
      }),
    };
  }),

  setStatus: (status) => set({ status }),
  setConnection: (connection) => set({ connection }),
  setError: (error) => set({ error, status: 'error' }),
  reset: () => set({ measure: null, status: 'idle', error: null, receivedAt: null, pendingId: null }),
}));

// Stable selectors — defined once, referenced by hooks below to keep
// reference equality across renders.
const selBarcode = (s) => s.measure?.barcode ?? '';
const selCodeSource = (s) => s.measure?.codeSource ?? null;
const selLiveWeight = (s) => s.liveWeight;
const selLiveStable = (s) => s.liveStable;
const selSerialStatus = (s) => ({ status: s.serialStatus, error: s.serialError, path: s.serialPath });
const selEventLog = (s) => s.eventLog;
const selPendingId = (s) => s.pendingId;
const selDailyCounter = (s) => s.dailyCounter;
const selWeight = (s) => s.measure?.weight ?? null;
const selDims = (s) => ({ len: s.measure?.len ?? null, width: s.measure?.width ?? null, height: s.measure?.height ?? null });
const selVol = (s) => s.measure?.vol ?? null;
const selStatus = (s) => s.status;
const selConnection = (s) => s.connection;
const selDatetime = (s) => s.measure?.datetime ?? null;

export const useBarcode = () => useMeasureStore(selBarcode);
export const useCodeSource = () => useMeasureStore(selCodeSource);
export const useLiveWeight = () => useMeasureStore(selLiveWeight);
export const useLiveStable = () => useMeasureStore(selLiveStable);
export const useSerialStatus = () => useMeasureStore(selSerialStatus, shallow);
export const useEventLog = () => useMeasureStore(selEventLog);
export const usePendingId = () => useMeasureStore(selPendingId);
export const useDailyCounter = () => useMeasureStore(selDailyCounter);
export const useWeight = () => useMeasureStore(selWeight);
export const useDims = () => useMeasureStore(selDims, shallow);
export const useVol = () => useMeasureStore(selVol);
export const useStatus = () => useMeasureStore(selStatus);
export const useConnection = () => useMeasureStore(selConnection);
export const useDatetime = () => useMeasureStore(selDatetime);

// Snapshot getter for non-reactive consumers (QR generation on demand)
export const getMeasureSnapshot = () => useMeasureStore.getState().measure;
