import { create } from 'zustand';
import { shallow } from 'zustand/shallow';

// Pending ID is the next package label, generated by the user clicking
// "Nouveau colis". When a measurement arrives, it inherits this ID
// (overriding any incoming barcode), then the slot clears so the next
// click is required before a new package is recorded.
const COUNTER_KEY = 'mobilax.dailyCounter';

function loadCounter() {
  try {
    const raw = JSON.parse(localStorage.getItem(COUNTER_KEY) || '{}');
    if (raw.day === todayKey()) return raw.value || 0;
  } catch {}
  return 0;
}

function saveCounter(value) {
  try { localStorage.setItem(COUNTER_KEY, JSON.stringify({ day: todayKey(), value })); } catch {}
}

function todayKey() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
}

function appendEvent(log, entry) {
  const next = [...log, { ...entry, t: Date.now() }];
  return next.length > 100 ? next.slice(-100) : next;
}

function buildMeasure(id, weight, d) {
  return {
    barcode: id,
    codeSource: 'generated',
    datetime: new Date().toISOString().replace('T', ' ').slice(0, 19),
    weight,
    len: d.len ?? null,
    width: d.width ?? null,
    height: d.height ?? null,
    vol: d.vol ?? null,
  };
}

// Per-axis median of a small array of dim frames. Robust to outliers and
// removes the 1–2 mm camera jitter that would otherwise bleed into the QR.
function medianDims(history, fallback) {
  const arr = (history || []).filter(Boolean);
  if (arr.length === 0) return fallback || {};
  const median = (key) => {
    const xs = arr.map((d) => d?.[key]).filter((v) => v != null).sort((a, b) => a - b);
    if (xs.length === 0) return null;
    const mid = Math.floor(xs.length / 2);
    return xs.length % 2 ? xs[mid] : Math.round(((xs[mid - 1] + xs[mid]) / 2) * 100) / 100;
  };
  return {
    len: median('len'),
    width: median('width'),
    height: median('height'),
    vol: median('vol'),
  };
}

function dimsTxtOf(d) {
  if (!d || (!d.len && !d.width && !d.height)) return '';
  return ` | L${d.len ?? '?'}×l${d.width ?? '?'}×h${d.height ?? '?'} mm`;
}

function buildPendingId(n) {
  const d = new Date();
  const ymd = `${String(d.getFullYear()).slice(2)}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;
  return `MBX-${ymd}-${String(n).padStart(4, '0')}`;
}

// Operator workflow state machine. The camera only emits volume frames on
// scene changes (placing/removing the package), so we can't expect a steady
// stream — but each placement does produce a burst of frames, which is
// enough to lock a measurement automatically.
//
// idle      → no package
// detected  → weight crossed the placement threshold; waiting for stability
//             and a volume reading from the camera
// locked    → measurement frozen with current values + auto-generated ID
// relocking → was locked, then a significant weight change was detected
//             (swap / partial lift). The previous measure (and QR) stays
//             visible while we wait for a new stable reading to re-lock.
const PLACE_THRESHOLD_KG = 0.1;     // weight above this = package placed
const REMOVE_THRESHOLD_KG = 0.05;   // weight below this = package removed
const MIN_STABLE_MS = 700;          // weight must hold this long before lock
// Fraction of the locked weight below which we treat the change as a swap
// (drop to <50% of the locked value → relocking). Catches quick swaps that
// don't drop weight all the way to zero.
const RELOCK_DROP_RATIO = 0.5;

export const useMeasureStore = create((set, get) => ({
  measure: null,
  status: 'idle',          // 'idle' | 'detected' | 'locked' | 'relocking'
  connection: 'disconnected',
  error: null,
  receivedAt: null,
  measureCount: 0,

  pendingId: null,         // legacy: retained so manual flow still works
  dailyCounter: loadCounter(),

  liveWeight: null,
  liveStable: false,
  liveDims: null, // { len, width, height, vol } — latest frame from the camera bridge
  // Rolling buffer of recent volume frames. At lock time we take the
  // median per axis to filter sensor jitter (1–2 mm noise on dims is normal).
  liveDimsHistory: [],
  armedAt: null,
  weightAtArm: null,
  dimsAtArm: null,
  // Auto-flow timestamps: when weight crossed the placement threshold and
  // when it last looked stable. Used to enforce the MIN_STABLE_MS dwell.
  detectedAt: null,
  stableSince: null,
  setLiveDims: (dims) => set((s) => {
    // The camera also emits "empty scene" frames when the package is
    // removed (all dims null or zero). Ignore them so they don't pollute
    // the median window — otherwise a quick swap to a different-size box
    // ends up with mixed-history dims, and the lock picks a wrong value.
    const isEmpty = !dims || (
      (dims.len == null || dims.len === 0) &&
      (dims.width == null || dims.width === 0) &&
      (dims.height == null || dims.height === 0)
    );
    if (isEmpty) return {};

    const hist = [...s.liveDimsHistory, dims];
    const trimmed = hist.length > 5 ? hist.slice(-5) : hist;
    const next = { liveDims: dims, liveDimsHistory: trimmed };

    // If we were waiting to lock (status=detected/relocking, weight stable,
    // weight above threshold) and dims just arrived, fire the lock now so
    // the measurement includes the camera reading.
    const w = s.liveWeight;
    const above = w != null && w >= PLACE_THRESHOLD_KG;
    const wantsLock = s.liveStable && above
      && (s.status === 'detected' || s.status === 'relocking' || s.pendingId);
    if (wantsLock) {
      let id, counter = s.dailyCounter;
      if (s.pendingId) {
        id = s.pendingId;
      } else {
        counter = s.dailyCounter + 1;
        saveCounter(counter);
        id = buildPendingId(counter);
      }
      const d = medianDims(trimmed, dims);
      next.measure = buildMeasure(id, w, d);
      next.status = 'locked';
      next.dailyCounter = counter;
      next.receivedAt = Date.now();
      next.measureCount = s.measureCount + 1;
      next.pendingId = null;
      next.armedAt = null;
      next.detectedAt = null;
      next.stableSince = null;
      next.eventLog = appendEvent(s.eventLog, {
        kind: 'measure.locked',
        text: `Auto — ${id} | ${w.toFixed(2)} kg${dimsTxtOf(d)} (caméra)`,
      });
    }
    return next;
  }),
  serialStatus: 'unknown', // 'open' | 'error' | 'closed' | 'unknown'
  serialError: null,
  serialPath: null,
  eventLog: [], // chronological feed of activity (user actions + serial + measure lifecycle)
  setSerialStatus: ({ status, error, path }) => set({ serialStatus: status, serialError: error ?? null, serialPath: path ?? null }),
  pushEvent: (entry) => set((s) => {
    const next = [...s.eventLog, { ...entry, t: Date.now() }];
    return { eventLog: next.length > 100 ? next.slice(-100) : next };
  }),
  setLiveWeight: ({ weight, stable }) => set((s) => {
    const now = Date.now();
    const next = { liveWeight: weight, liveStable: !!stable };
    if (weight == null) return next;

    const above = weight >= PLACE_THRESHOLD_KG;
    const below = weight <= REMOVE_THRESHOLD_KG;
    const lockedWeight = s.measure?.weight;
    const significantDrop = lockedWeight != null && weight < lockedWeight * RELOCK_DROP_RATIO;

    // ─── Full removal from locked/relocking → back to idle ──────────
    // Keep `measure` so the QR stays scannable until a new lock replaces
    // it. Keep `liveDims` (last known dims) as a fallback so a same-size
    // next carton — for which the camera won't re-emit on identical scene
    // — can still auto-lock. Clear the history so the median doesn't keep
    // averaging old frames once new ones arrive for a different-size box.
    if ((s.status === 'locked' || s.status === 'relocking') && below) {
      next.status = 'idle';
      next.detectedAt = null;
      next.stableSince = null;
      next.liveDimsHistory = [];
      next.eventLog = appendEvent(s.eventLog, {
        kind: 'user.new',
        text: `Colis retiré (${weight.toFixed(2)} kg) — QR conservé`,
      });
      return next;
    }

    // ─── Swap detected: significant drop while locked → relocking ──
    // The previous measure (and its QR) stays visible. We wait for a
    // new stable reading to re-lock with fresh values. Clear the dims
    // history so the new lock isn't biased by the previous package's
    // frames; liveDims stays as fallback for same-size cartons.
    if (s.status === 'locked' && significantDrop) {
      next.status = 'relocking';
      next.detectedAt = now;
      next.stableSince = null;
      next.liveDimsHistory = [];
      const dropPct = Math.round((1 - weight / lockedWeight) * 100);
      next.eventLog = appendEvent(s.eventLog, {
        kind: 'user.new',
        text: `Changement détecté (-${dropPct}% : ${weight.toFixed(2)} kg) — attente nouvelle mesure`,
      });
      return next;
    }

    // While locked with no significant change, ignore weight updates.
    if (s.status === 'locked') return next;

    // ─── Detect placement (visual feedback) ──────────────────────────
    if (s.status === 'idle' && above) {
      next.status = 'detected';
      next.detectedAt = now;
      next.eventLog = appendEvent(s.eventLog, {
        kind: 'user.new',
        text: `Colis détecté (${weight.toFixed(2)} kg) — attente stabilisation`,
      });
      // Don't return; fall through so a single 'stable' event in the
      // same dispatch can lock immediately.
    }

    // Cancel detection if weight goes back below threshold.
    if (s.status === 'detected' && below) {
      next.status = 'idle';
      next.detectedAt = null;
      return next;
    }

    // ─── Lock condition ─────────────────────────────────────────────
    // The bridge's STABLE_WINDOW_MS already enforces a dwell window
    // before raising stable=true, so we don't re-time. We need usable
    // dims — either a fresh frame in history, or a cached liveDims from
    // a previous lock (same-size next carton, camera won't re-emit).
    // Also fires from 'relocking' so a swap can re-lock once the new
    // weight stabilises above the placement threshold.
    const hasDims = (s.liveDimsHistory && s.liveDimsHistory.length > 0) || s.liveDims != null;
    const wantsLock = stable && above && hasDims
      && (s.status === 'detected' || s.status === 'relocking' || next.status === 'detected' || s.pendingId);

    if (wantsLock) {
      let id, counter = s.dailyCounter;
      if (s.pendingId) {
        id = s.pendingId;
      } else {
        counter = s.dailyCounter + 1;
        saveCounter(counter);
        id = buildPendingId(counter);
      }
      const d = medianDims(s.liveDimsHistory, s.liveDims);
      next.measure = buildMeasure(id, weight, d);
      next.status = 'locked';
      next.dailyCounter = counter;
      next.receivedAt = now;
      next.measureCount = s.measureCount + 1;
      next.pendingId = null;
      next.armedAt = null;
      next.detectedAt = null;
      next.stableSince = null;
      next.eventLog = appendEvent(s.eventLog, {
        kind: 'measure.locked',
        text: `Auto — ${id} | ${weight.toFixed(2)} kg${dimsTxtOf(d)}`,
      });
    }

    return next;
  }),

  // Snapshot the current live values into a finalised measure right now.
  // Works in any state (idle / detected / locked) — auto-generates an ID,
  // grabs the latest weight + dims, and freezes them. The escape hatch
  // when auto-lock can't fire (heavy vibration, partial scene, etc.).
  freezeNow: () => set((s) => {
    const counter = s.dailyCounter + 1;
    saveCounter(counter);
    const id = s.pendingId || buildPendingId(counter);
    const d = s.liveDims || {};
    const w = s.liveWeight;
    const m = buildMeasure(id, w, d);
    return {
      measure: m,
      status: 'locked',
      dailyCounter: s.pendingId ? s.dailyCounter : counter,
      receivedAt: Date.now(),
      measureCount: s.measureCount + 1,
      pendingId: null,
      armedAt: null,
      detectedAt: null,
      stableSince: null,
      eventLog: appendEvent(s.eventLog, {
        kind: 'measure.locked',
        text: `Figé manuellement — ${id} | ${w ?? '—'} kg${dimsTxtOf(d)}`,
      }),
    };
  }),

  // Legacy alias (kept for backward compat with any caller that still
  // references validateNow).
  validateNow: () => get().freezeNow(),

  // Manual reset back to idle so the auto-flow can fire again on the
  // current package without having to physically remove and re-place it.
  // Useful when an early auto-lock missed the camera dims.
  // Keep `measure` + dims so the previous QR stays scannable until the
  // next lock replaces it.
  resetSession: () => set((s) => ({
    status: 'idle',
    detectedAt: null,
    stableSince: null,
    pendingId: null,
    armedAt: null,
    eventLog: appendEvent(s.eventLog, {
      kind: 'user.new',
      text: 'Session réinitialisée — auto-flow réarmé',
    }),
  })),

  // Generates the next pending ID and arms the slot.
  // Records the live values at the moment of arming so we can reject
  // stale auto-locks (next package picking up the previous package's
  // weight + dimensions because nothing changed on the bus yet).
  newPackage: () => set((s) => {
    const next = s.dailyCounter + 1;
    saveCounter(next);
    const id = buildPendingId(next);
    return {
      dailyCounter: next,
      pendingId: id,
      status: 'measuring',
      armedAt: Date.now(),
      weightAtArm: s.liveWeight,
      dimsAtArm: s.liveDims,
      // Visually clear the camera dims; the next bridge frame (~150ms)
      // refills them so the operator sees that a new measurement landed.
      liveDims: null,
      eventLog: appendEvent(s.eventLog, { kind: 'user.new', text: `Nouveau colis armé — ${id}` }),
    };
  }),

  setMeasure: (measure, source = 'manual') => set((s) => {
    const m = s.pendingId
      ? { ...measure, barcode: s.pendingId, codeSource: 'generated' }
      : measure;
    const dimsTxt = (m.len || m.width || m.height)
      ? ` | L${m.len ?? '?'}×l${m.width ?? '?'}×h${m.height ?? '?'} mm`
      : '';
    return {
      measure: m,
      status: 'ready',
      error: null,
      receivedAt: Date.now(),
      measureCount: s.measureCount + 1,
      pendingId: null,
      armedAt: null,
      eventLog: appendEvent(s.eventLog, {
        kind: 'measure.locked',
        text: `Mesure verrouillée (${source}) — ${m.barcode} | ${m.weight ?? '—'} kg${dimsTxt}`,
      }),
    };
  }),

  setStatus: (status) => set({ status }),
  setConnection: (connection) => set({ connection }),
  setError: (error) => set({ error, status: 'error' }),
  reset: () => set({ measure: null, status: 'idle', error: null, receivedAt: null, pendingId: null }),
}));

// Stable selectors — defined once, referenced by hooks below to keep
// reference equality across renders.
const selBarcode = (s) => s.measure?.barcode ?? '';
const selCodeSource = (s) => s.measure?.codeSource ?? null;
const selLiveWeight = (s) => s.liveWeight;
const selLiveStable = (s) => s.liveStable;
const selLiveDims = (s) => s.liveDims;
const selSerialStatus = (s) => ({ status: s.serialStatus, error: s.serialError, path: s.serialPath });
const selEventLog = (s) => s.eventLog;
const selPendingId = (s) => s.pendingId;
const selDailyCounter = (s) => s.dailyCounter;
// "Fresh" means: a pending ID is armed AND either weight or dims have moved
// since arming. Used by the UI to encourage the operator to wait for new data.
const selFreshness = (s) => {
  if (!s.pendingId || !s.armedAt) return 'idle';
  const elapsed = Date.now() - s.armedAt;
  const armW = s.weightAtArm;
  const w = s.liveWeight;
  const weightChanged = (armW != null && w != null) && Math.abs(w - armW) >= 0.05;
  const dimsArrived = s.liveDims && (
    !s.dimsAtArm
    || s.liveDims.len !== s.dimsAtArm.len
    || s.liveDims.width !== s.dimsAtArm.width
    || s.liveDims.height !== s.dimsAtArm.height
  );
  if (weightChanged || dimsArrived) return 'fresh';
  if (elapsed > 1500) return 'stale-but-armed';
  return 'awaiting';
};
const selWeight = (s) => s.measure?.weight ?? null;
const selDims = (s) => ({ len: s.measure?.len ?? null, width: s.measure?.width ?? null, height: s.measure?.height ?? null });
const selVol = (s) => s.measure?.vol ?? null;
const selStatus = (s) => s.status;
const selConnection = (s) => s.connection;
const selDatetime = (s) => s.measure?.datetime ?? null;

export const useBarcode = () => useMeasureStore(selBarcode);
export const useCodeSource = () => useMeasureStore(selCodeSource);
export const useLiveWeight = () => useMeasureStore(selLiveWeight);
export const useLiveStable = () => useMeasureStore(selLiveStable);
export const useLiveDims = () => useMeasureStore(selLiveDims, shallow);
export const useSerialStatus = () => useMeasureStore(selSerialStatus, shallow);
export const useEventLog = () => useMeasureStore(selEventLog);
export const usePendingId = () => useMeasureStore(selPendingId);
export const useDailyCounter = () => useMeasureStore(selDailyCounter);
export const useFreshness = () => useMeasureStore(selFreshness);
export const useWeight = () => useMeasureStore(selWeight);
export const useDims = () => useMeasureStore(selDims, shallow);
export const useVol = () => useMeasureStore(selVol);
export const useStatus = () => useMeasureStore(selStatus);
export const useConnection = () => useMeasureStore(selConnection);
export const useDatetime = () => useMeasureStore(selDatetime);

// Snapshot getter for non-reactive consumers (QR generation on demand)
export const getMeasureSnapshot = () => useMeasureStore.getState().measure;
